"use client";

import { useEffect, useRef } from "react";
import { useParams } from "next/navigation";
import { useAuth } from "@/lib/auth-context";
import ChatHeader from "@/components/ChatHeader";
import ChatInput from "@/components/ChatInput";
import ChatMainFrame from "@/components/layout/ChatMainFrame";
import ChatThread from "@/components/chat/ChatThread";
import { useSidebar } from "../../layout";
import { useChatSession } from "@/hooks/useChatSession";

export default function ChatPage() {
    const params = useParams();
    const { user, isAuthed } = useAuth();
    const { setSelectedCharacterId } = useSidebar();
    const chatId = params.id as string;

    const {
        character,
        messages,
        isStreaming,
        isLoading,
        error,
        handleSelectCandidate,
        handleRegenAssistant,
        handleEditUser,
        handleSendMessage,
    } = useChatSession({
        chatId,
        isAuthed,
        canSend: Boolean(user),
        setSelectedCharacterId,
    });

    const messagesEndRef = useRef<HTMLDivElement>(null);
    const scrollRootRef = useRef<HTMLDivElement>(null);
    const shouldAutoScrollRef = useRef(true);

    useEffect(() => {
        const root = scrollRootRef.current;
        if (!root) return;

        const updateShouldAutoScroll = () => {
            const distanceToBottom = root.scrollHeight - root.scrollTop - root.clientHeight;
            shouldAutoScrollRef.current = distanceToBottom <= 160;
        };

        updateShouldAutoScroll();
        root.addEventListener("scroll", updateShouldAutoScroll, { passive: true });

        return () => {
            root.removeEventListener("scroll", updateShouldAutoScroll);
        };
    }, []);

    useEffect(() => {
        if (!shouldAutoScrollRef.current) return;
        const raf = requestAnimationFrame(() => {
            messagesEndRef.current?.scrollIntoView({
                behavior: isStreaming ? "auto" : "smooth",
                block: "end",
            });
        });
        return () => cancelAnimationFrame(raf);
    }, [messages, isStreaming]);

    const headerContent = (
        <div className="w-full">
            <ChatHeader character={character} />
        </div>
    );

    const threadContent = (
        <ChatThread
            character={character}
            messages={messages}
            isLoading={isLoading}
            error={error}
            isStreaming={isStreaming}
            userAvatar={user?.avatar_url || "/default-avatar.svg"}
            messagesEndRef={messagesEndRef}
            onSelectCandidate={handleSelectCandidate}
            onRegenAssistant={handleRegenAssistant}
            onEditUser={handleEditUser}
        />
    );

    const composerContent = character && !error ? (
        <ChatInput
            onSend={handleSendMessage}
            disabled={isStreaming}
            roleName={character.name}
        />
    ) : (
        <div className="text-base mx-auto px-4 sm:px-6 lg:px-16">
            <div className="mx-auto mb-4 w-full max-w-[768px]">
                <div
                    className="h-14 w-full"
                    style={{
                        borderRadius: "28px",
                        backgroundColor: "#FFFFFF",
                        boxShadow: "0 1px 2px rgba(0, 0, 0, 0.12)",
                    }}
                />
            </div>
        </div>
    );

    return (
        <ChatMainFrame
            scrollRootRef={scrollRootRef}
            header={headerContent}
            thread={threadContent}
            composer={composerContent}
            disclaimer={<div>The content is generated by AI.Please check important info.</div>}
        />
    );
}
