import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Terms of Use – ParlaSoul",
  description: "Terms of Use for ParlaSoul",
};

const LAST_UPDATED = "April 14, 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-100 px-6 py-7 max-sm:py-5">
        <div className="mx-auto flex max-w-3xl items-center gap-2.5">
          <Image src="/icon.svg" alt="ParlaSoul" width={24} height={24} className="rounded-md" />
          <span className="text-base font-semibold tracking-tight">ParlaSoul</span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12 pb-20 max-sm:py-8">
        <h1 className="text-3xl font-bold tracking-tight">Terms of Use</h1>
        <p className="mt-2 text-sm text-gray-400">Last updated: {LAST_UPDATED}</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-gray-600">
          {/* 1 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">1. Acceptance of Terms</h2>
            <p className="mt-2">
              By accessing or using ParlaSoul (&quot;the Service&quot;), you agree to be bound by these
              Terms of Use (&quot;Terms&quot;). If you do not agree, do not use the Service. These Terms
              apply to all visitors, users, and others who access the Service.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">2. Description of Service</h2>
            <p className="mt-2">
              ParlaSoul is an AI-powered character roleplay platform that allows users to interact
              with virtual AI characters through text and voice conversations. The Service is provided
              &quot;as is&quot; and may be modified, suspended, or discontinued at any time without notice.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">3. User Accounts</h2>
            <p className="mt-2">
              You may need to create an account to access certain features. You are responsible for
              maintaining the confidentiality of your account credentials and for all activities under
              your account. You must be at least 13 years old to use the Service. If you are under 18,
              you represent that your parent or legal guardian has reviewed and agreed to these Terms.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">4. User Conduct</h2>
            <p className="mt-2">You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its related systems.</li>
              <li>Interfere with or disrupt the integrity or performance of the Service.</li>
              <li>Impersonate any person or entity, or falsely state or misrepresent your affiliation.</li>
              <li>Use the Service to generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.</li>
              <li>Reverse-engineer, decompile, disassemble, or otherwise attempt to discover the source code of the Service.</li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">5. AI-Generated Content</h2>
            <p className="mt-2">
              Conversations with AI characters are generated by artificial intelligence and do not
              represent the views, opinions, or statements of ParlaSoul or its team. AI-generated
              content may be inaccurate, incomplete, or offensive. You acknowledge that the Service
              provides simulated interactions and should not be relied upon for professional advice,
              including but not limited to medical, legal, financial, or psychological guidance.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">6. Intellectual Property</h2>
            <p className="mt-2">
              The Service and its original content (excluding user-provided content), features, and
              functionality are owned by ParlaSoul and are protected by international copyright,
              trademark, and other intellectual property laws. You retain ownership of the content
              you submit to the Service. By using the Service, you grant ParlaSoul a limited,
              non-exclusive license to process your input for the purpose of providing the Service.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">7. Payments and Subscriptions</h2>
            <p className="mt-2">
              Certain features of the Service may require payment. All fees are listed on our pricing
              page and are subject to change with notice. Subscriptions automatically renew unless
              cancelled before the renewal date. Refunds are handled on a case-by-case basis; please
              contact support for assistance.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">8. Termination</h2>
            <p className="mt-2">
              We may terminate or suspend your account and access to the Service at our sole
              discretion, without prior notice, for conduct that we believe violates these Terms or
              is harmful to other users, us, or third parties. Upon termination, your right to use
              the Service will immediately cease.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">9. Disclaimer of Warranties</h2>
            <p className="mt-2">
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. To the fullest
              extent permitted by law, ParlaSoul disclaims all warranties, express or implied,
              including implied warranties of merchantability, fitness for a particular purpose, and
              non-infringement. We do not warrant that the Service will be uninterrupted, timely,
              secure, or error-free.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">10. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by applicable law, ParlaSoul and its directors,
              employees, partners, agents, suppliers, or affiliates shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including loss of
              profits, data, or other intangible losses, resulting from your access to or use of
              (or inability to access or use) the Service.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">11. Changes to Terms</h2>
            <p className="mt-2">
              We reserve the right to modify or replace these Terms at any time. Material changes
              will be notified via the Service or by email. Your continued use of the Service after
              any such changes constitutes acceptance of the new Terms.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">12. Governing Law</h2>
            <p className="mt-2">
              These Terms shall be governed by and construed in accordance with applicable laws,
              without regard to conflict of law provisions. Any disputes arising under these Terms
              shall be resolved through good-faith negotiation, and if unresolved, through binding
              arbitration.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900">13. Contact</h2>
            <p className="mt-2">
              If you have questions about these Terms, please contact us at{" "}
              <a href="mailto:verify@parlasoul.com" className="text-gray-900 underline underline-offset-2 hover:text-black">
                verify@parlasoul.com
              </a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
